### ISSUE TITLE
Create Simple Login Functionality

### ISSUE THREAD

**Issue by nrhubbar** [rustbridge/rustbridge.io#6]
Currently this is just a static page. In the future we will want the ability to allow for dynamically created data. 

- [x] Spin up Postgres and get started with [diesel](http://diesel.rs/) #5 
- [x] Create Controller Methods to Handle Creating Users #8 
- [x] Create Controller Methods to Handle Logging in Users #9
- [x] Create Login Views #7
